on: 
  push:
    branches:
      - master

name: Node.js

env:
  AZURE_WEBAPP_NAME: mscgroup    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'build'            # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x'   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
           
    - name: Use Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
               
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
